apiVersion: v1
kind: Service
metadata:
  name: microservicio-api-gateway
spec:
  selector:
    app: microservicio-api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer