name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
        ecr: auto
        logout: true
          
    - name: Build the Docker image
      run: docker build --build-arg MICROSERVICIO_SEGURIDAD_URI=${{ secrets.MICROSERVICIO_SEGURIDAD_URI }} --build-arg MICROSERVICIO_PRODUCTOS_URI=${{ secrets.MICROSERVICIO_PRODUCTOS_URI }} --build-arg MICROSERVICIO_PEDIDOS_URI=${{ secrets.MICROSERVICIO_PEDIDOS_URI }} --build-arg MICROSERVICIO_CHAT_URI=${{ secrets.MICROSERVICIO_CHAT_URI }} --build-arg MICROSERVICIO_REGISTRO_URI=${{ secrets.MICROSERVICIO_REGISTRO_URI }} -t ${{secrets.DOCKER_HUB_USERNAME}}/ec-api-gtw:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/ec-api-gtw:latest
