name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      MICROSERVICIO_SEGURIDAD_URI: ${{ secrets.MICROSERVICIO_SEGURIDAD_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/ec-api-gtw:latest .
